version: "3.9"

services:
  db:
    image: postgres:latest
    container_name: nextjs-better-auth-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: db
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  pgdata:
    driver: local
    driver_opts:
      type: none
      device: ${PWD}/.data/pgdata
      o: bind
